"""adding column

Revision ID: 54a30a82c9d8
Revises: d2ed592744f6
Create Date: 2025-09-04 16:20:01.227872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a30a82c9d8'
down_revision: Union[str, Sequence[str], None] = 'd2ed592744f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###
